
stages:
  - deploy-prod

variables:
  DOCKER_IMAGE_PROD: "nist775hit/codeset-authoring-tool-prod"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375  # Ensure Docker commands connect to the DinD service
  DOCKER_TLS_CERTDIR: ""          # Disable TLS for Docker-in-Docker

deploy_prod:
  stage: deploy-prod
  script:
    - echo "Deploying codeset authoring tool in hit dev"
    - cd /sites/apps/hl7v2-codeset-authoring-tool-deployment
    # - git pull 
    - cd containers/apps/prod/scripts
    - bash start.sh
  tags:
    - hitdev
    - shell
  when: manual
  allow_failure: false 